require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Exclude:
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
