# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: awrence 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "awrence"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dave Hrycyszyn"]
  s.date = "2017-01-13"
  s.description = "Have you ever needed to automatically convert Ruby-style\n    snake_case to CamelCase or camelBack hash keys?\n\n    Awrence to the rescue.\n\n    This gem recursively converts all snake_case keys in a hash\n    structure to camelBack.  "
  s.email = "dave.hrycyszyn@headlondon.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "awrence.gemspec",
    "lib/awrence.rb",
    "lib/awrence/ext/hash/to_camel_keys.rb",
    "test/awrence/ext/hash/to_camel_keys_test.rb",
    "test/helper.rb",
    "test/test_awrence.rb"
  ]
  s.homepage = "http://github.com/futurechimp/awrence"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Camelize your snake keys when working with JSON APIs"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.3"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 4.2"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.3"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 4.2"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.3"])
  end
end

